### ISSUE TITLE
needs manual

### ISSUE THREAD

**Issue by severak** [rxi/lite#103]
saw this on hackers news and decided to try it out.

It looks very nice. However it desperately needs some manual, intro, helpfile or noobmode. There is no help command or something similar.

I did not find out how to create new project or open folder as project. 

If you use `Core: Open File` you get menu with listing files of current working directory/program directory, not Open File dialog as I would expect.

However, it seems to be somewhat hackable. I will try to create `introduction` plugin.

**Comment by harikt** [comment]
I have kept a symbolic link from `/usr/local/bin/lite` to `/home/hari/lite/lite` .

and run lite from cli. 

`lite /path/to/project-folder`

You can run commands via pressing `ctrl+shift+p` . When you start typing you can see lots of commands.

There is already an open issue https://github.com/rxi/lite/issues/65 . Hope that helps you to do more with lite. 

I am not a lua guy, but I tried to peek into the code and have learned a few. So I believe you will also be able to do those things. In the coming days, may be we can all do some writings to help this project with more docs.

I will try to find some time. But I cannot guarantee due to personal needs.

**Comment by sp00ck** [comment]
And how disable bar (file in folder) on left?
Simple information about format file

**Comment by sudo-Ilyria** [comment]
There is no documentation on how to install the plugins and themes . Even if it is trivial that you place in the stuff in the plugins folder but how do i make them load/work ? For example I have the bigclock plugin but how do i make it appear ? There is no clock when opening it .

**Comment by bbs4murai** [comment]
> For example I have the bigclock plugin but how do i make it appear ? There is no clock when opening it .

You can open the `bigclock` by running the command `Big Clock Open`. (`ctrl+shift+p` to run a command)

**Comment by bokunodev** [comment]
i write some plugins by look at already available plugins for my personal use.
but where i can found documantation about the available API ? and how to use them ?
