### ISSUE TITLE
Sequence of keys to perform a command

### ISSUE THREAD

**Issue by dacap** [rxi/lite#121]
Are plans to specify a sequence of keys in keymaps? E.g.
```
keymap.add {
  ["ctrl+k, ctrl+c"] = "doc:toggle-line-comments"
}
```
Would be a PR to do this accepted? What should be the syntax to separate each key?

**Comment by rxi** [comment]
I'm unsure if you meant that you're specifying two separate keys as a sequence (eg. this would bind both `ctrl+k` and `ctrl+c`) or if you meant that pressing the sequence of `ctrl+k` followed by `ctrl+c` would perform the command. Either way this is not something I plan to support in lite. The former would probably take more lines of code to implement than it saves in your key mapping due to how infrequently one would do this, the latter is outside the scope of the built-in keymap system (this is something that could be [implemented as a plugin](https://github.com/a327ex/lite-plugins/blob/master/plugins/modalediting.lua) though).

**Comment by dacap** [comment]
I was looking for a sequence of keys (`ctrl+k` followed by `ctrl+c`), I think the plugin approach will be enough.
