### ISSUE TITLE
New instance when dropping a folder onto lite

### ISSUE THREAD

**Issue by tDwtp** [rxi/lite#154]
as stated here:
https://github.com/rxi/lite/commit/7517d0ef552c89cc24e0589a8df8eb9648217e24#commitcomment-39879404

Gif showing the issue here:
![2020-06-15-14-30-50_1](https://user-images.githubusercontent.com/2230360/84660173-c1940280-af18-11ea-9652-a8d414289226.gif)

**Comment by tDwtp** [comment]
Found the culprit:
https://github.com/tDwtp/lite/blob/1db1f0bcebd54878a0415deda91c92b6e03acbd3/data/core/init.lua#L345

(basically this was intentional?)
I am going to check on how to reload the RootView, so you don't to open a new instance.

**Comment by rxi** [comment]
As you pointed out this is intentional behaviour, it may be something which is tweaked in the future (for example: automatically closing the current instance if there are no documents open)

> I am going to check on how to reload the RootView, so you don't to open a new instance.

Assuming you meant the TreeView (the RootView is the layout system). The TreeView is based around the "project directory". As a rule lite can have *one* project directory set, which is set at start up and cannot be changed without restarting lite. All parts of lite (including plugins) are allowed to assume this is the case -- changing the project directory once lite has initialised isn't something that will be supported.

**Comment by tDwtp** [comment]
I noticed I can't just change the TreeView without causing issues, so I wanted to reload the UI without reloading everything. good to know it won't work...
