### ISSUE TITLE
[question] how to perform regex search and replace ?

### ISSUE THREAD

**Issue by bokunodev** [rxi/lite#175]
how to perform regex search and replace ?
`find replace: replace pattern` does not evaluate regex.

**Comment by rxi** [comment]
Regex is not supported, lite instead uses [lua patterns](https://www.lua.org/manual/5.1/manual.html#5.4.1)

**Comment by bokunodev** [comment]
how to match **line break** with lua pattern ?

**Comment by bokunodev** [comment]
oh, i can do it within plugins. i think i will write another plugns to cover this issue.
I'm a little disappointed because I can't do it with `search & replace`.
but, thank you for the responses.

**Comment by Himura2la** [comment]
Isn't it what the `"find-replace:replace-pattern"` supposed to do?
But it does not, looks like my `\n` is being escaped before getting into the handler

![image](https://user-images.githubusercontent.com/7802808/162375336-b608b010-fe7b-41bf-abcd-f4449e45c56d.png)

I guess the reason is here https://github.com/rxi/lite/blob/master/data/core/doc/init.lua#L208-L209
since this function is used in `CommandView:submit()`
