### ISSUE TITLE
Horizontal Scrolling Threashold

### ISSUE THREAD

**Issue by Gavin-Holt** [rxi/lite#181]
Hi,

I find that the automatic horizontal scrolling cuts in at about 80% of the width of the text window. This is unusual/dis-concerting  when compared with other non-wrapping text editors.

Q1. Is there a Lua setting to change this to 100% - so the screen only hscrolls when strictly necessary?

Kind Regards Gavin Holt

**Comment by rxi** [comment]
This isn't currently provided as a configuration option. The logic for horizontal scrolling is in the `DocView:scroll_to_make_visible(line, col)` if this is a change you want to patch into your local copy in the mean time or add as a plugin.

**Comment by Gavin-Holt** [comment]
Many thanks I will give it a try.

G

**Comment by lordadamson** [comment]
In case anyone else is annoyed by this, here's what I did to fix it

Find `function DocView:scroll_to_make_visible(line, col)`

then change this line: `  local max = xoffset - self.size.x + gw + self.size.x / 5`

Change the 5 to 10 to have the automatic horizontal scrolling cut in at 90% instead of 80% which makes it much better.

Change that number to your liking.

Unfortunately I'm a noob, I don't know how to make a plugin out of that.
