### ISSUE TITLE
[Question] Move sidebar to right

### ISSUE THREAD

**Issue by fitrh** [rxi/lite#202]
I love this editor, and one of my habit is to have the sidebar on right, how i achieve this ?

**Comment by Tmpod** [comment]
It's very easy because lite is super "hackable" :P  In fact, the sidebar is simply a plugin that comes by default.

In this case, all you gotta do is go to the `treeview.lua` plugin file (which should be located at lite's `data/plugins`) folder and edit the line that contains `node:split("left", ...)`, and replace `"left"` with `"right"`.

The sidebar should then look like this:

![Screenshot_20201011_175413](https://user-images.githubusercontent.com/35771816/95684644-f6744580-0bea-11eb-8eaf-4a3169ce8e35.png)

---

A better solution for this would be to add a configuration field `treeview_side` which would default to `left` but could easily be changed without having to modify the plugin itself, just using the `data/user/init.lua` file. I am going to contribute this if @rxi agrees it's a nice addition.

**Comment by fitrh** [comment]
Thank you very much, didn't familiar with lua, i think i will start learning lua to customize this awesome editor
