### ISSUE TITLE
Feature Request: Multi-Cursor

### ISSUE THREAD

**Issue by sci4me** [rxi/lite#216]
Most editors allow the user to create multiple cursors for editing multiple lines of code at a time; it would be amazing to have that in lite. This is probably the biggest thing that would prevent lite from being my daily driver.

**Comment by Jipok** [comment]
https://github.com/rxi/lite/issues/150

**Comment by AqilCont** [comment]
I wonder when the app @rxi linked will release... It's been months since the last tweet about it hasn't it?
The main issue still stands though, as much as I would like this feature, lite might not have been made for it, and rxi probably doesn't care at all about implementing it.
Maybe it could still be added in other forks like [franko/lite-xl](https://github.com/franko/lite-xl).

**Comment by Tmpod** [comment]
> I wonder when the app @rxi linked will release... It's been months since the last tweet about it hasn't it?

That project is under a hiatus atm. Neither rxi or the other developer have time to work on rift, so we just have to wait...

> The main issue still stands though, as much as I would like this feature, lite might not have been made for it, and rxi probably doesn't care at all about implementing it.

Yes, rxi has stated he doesn't want to add multicursors to lite.

**Comment by AqilCont** [comment]
Yeah, I support that.

**Comment by IcedQuinn** [comment]
> That project is under a hiatus atm. Neither rxi or the other developer have time to work on rift, so we just have to wait...

For the benefit of anyone who runs in to this ticket in the future: this feature is part of the [Lite-XL fork](https://lite-xl.com/en/)
