### ISSUE TITLE
Add word wrap configuration

### ISSUE THREAD

**Issue by drmargarido** [rxi/lite#26]
Would be nice to be able to have word wrapping.

While coding usually I don't make lines that long, but when writing text for articles and other things in html or markdown it's common to have longer lines. And in markdown an enter will have meaning.

**Comment by rxi** [comment]
This is a little outside the scope of the project as it conflicts with the simplicity which `lite` aims for; it isn't something I planned to implement or support.

Regarding markdown a single newline is typically ignored as markdown as a format is supposed to be readable in plain-text. In general `lite` won't be the *best* choice of editor for markdown because of the lack of word wrapping (and live preview, and, currently, spellcheck); that being said I do use it myself for markdown, making liberal use of the `reflow` plugin (highlighting a paragraph or long line and hitting `ctrl+shift+q`).

**Comment by heyheyhello** [comment]
One usecase for this would be opening a minified JSON blob. Common for some developers. The workaround right now is to pretty print it and then open

**Comment by jmiskovic** [comment]
Even though the issue is closed, I add my vote to word wrapping option.

Lite does not support long lines well:

* there is no indication that line extends beyond the viewport
* horizontal scrolling is not possible with mouse and it's a bit clumsy by keyboard
* no by-page horizontal scrolling
* the text reflow pluggin is buggy (should open a different issue for that)

For comparison, a very minimal _nano_ editor shows `>` symbol for more content in line, doesn't have horizontal page scrolling, but has a soft wrap display feature.

Could the wrapping be made as a plugin?
It would have to replace text file content with the wrapped version, and also change back to unwrapped when saving the file.
