### ISSUE TITLE
Using a non-custom build system for lite

### ISSUE THREAD

**Issue by Cogitri** [rxi/lite#48]
Hello,

this has already been mentioned in https://github.com/rxi/lite/pull/45#issuecomment-626217708, but I think a non-custom build system like meson would greatly benefit lite, making it easier to build on more platforms. I could look into doing that while I package it for Alpine Linux.

**Comment by 1bardesign** [comment]
Seems a little counter to the minimalist approach of the project to pull in a multi-megabyte non-standard build dependency vs the current ~1kb total build scripts, which ran out of the box on linux here?

There are likely things that could be done for portability of the build scripts before pulling in more 3rd party code; for example maybe using `cc` instead of `gcc` if the project doesn't use any non-portable C code, to support clang-only build environments.

If the shell script approach was to be abandoned a boring old makefile or the lua-based [genie](https://github.com/bkaradzic/genie) seems more in-line with the philosophy?

**Comment by Cogitri** [comment]
> Seems a little counter to the minimalist approach of the project to pull in a multi-megabyte non-standard build dependency

At least in the linux world I'd argue meson is pretty standard these days - even core packages like glib are built with it

Even so, I'd argue that since meson is only required during buildtime its size doesn't matter *that* much and meson doesn't have any dependencies other than standard python3.

> which ran out of the box on linux here?

Then you probably have a setup that's pretty similiar to the dev's machine. Unfortunately it's pretty hard to get a custom build script right, so that it works on setups that aren't as standard.

> If the shell script approach was to be abandoned a boring old makefile or the lua-based genie seems more in-line with the philosophy?

A makefile would likely work fine too, but I don't see how genie would be more standard than meson

**Comment by 1bardesign** [comment]
> Unfortunately it's pretty hard to get a custom build script right, so that it works on setups that aren't as standard.

I agree with the sentiment in genera,  but for a Linux build the current requirements for lite are gcc (or properly configured ccache), and sdl2 dev files that gcc and the linker can find. The standard math library is also required at link time, afaik it's part of gcc.

This is hardly a difficult dev environment to ensure 😅 I can see using cc rather than specifically gcc helping, if the cli flags used are largely portable (I think they are?), but I don't see much harm in requiring gcc for building.

> I don't see how genie would be more standard than meson

I didn't say more standard, I said more in line with the project's philosophy of minimalism 😉

**Comment by rxi** [comment]
I'm in general agreement with @1bardesign 's points.

In summary: changing the build system to something more complex would solve a problem that doesn't exist, and cause several that do.
