### ISSUE TITLE
how do you open a folder?

### ISSUE THREAD

**Issue by marwahaha** [rxi/lite#57]
Hi, Cool project. I built it but I can't figure out how to open a folder. Ctrl-O only allows you to open files. What else should I try? 

P.S. Where can I look to help me through these sorts of questions?

**Comment by rxi** [comment]
Lite supports a single project-folder per-open-instance, which is always initialised on startup. This can be specified as a commandline argument when opening lite; if no folder is specified the current working directory is used.

Regarding questions: I'd recommend giving the code a quick skim if you're curious about something, there isn't much to look through. Otherwise making an issue like this is fine!
