### ISSUE TITLE
Allow plugins to be toggled on/off

### ISSUE THREAD

**Issue by Cogitri** [rxi/lite#60]
Hello,

it'd be nice if it were possible to toggle plugins on/off during runtime instead of lite loading and enabling all available plugins

**Comment by rxi** [comment]
This behaviour was a deliberate choice in term with lite's goal of simplicity, that is, to install a plugin you add a file and to uninstall it you delete that file. Because of how lite is generally structured and how plugins work (they can be written in a way that once they're loaded they'll never be asked to cleanly unload themselves), runtime enabling and disabling of plugins won't be supported.

**Comment by Cogitri** [comment]
Alright, that's fair. I'll go ahead and split each plugin into a subpackage for alpine linux then so that users can decide that they want.

**Comment by flamendless** [comment]
Maybe a plugin that will copy and delete the plugin file?

**Comment by Cogitri** [comment]
Ah, at least for distro packaging that wouldn't work, since the user won't have write access to the plugin files. Maybe just some blacklist in lite that would only be looked up during startup would work though?
