### ISSUE TITLE
Screen is not always redrawn when window is resized.

### ISSUE THREAD

**Issue by yyamdev** [rxi/lite#63]
Seen on Windows on version 1.03

When dragging the window so that it snaps between being maximised and smaller, the screen will sometimes not redraw when the window becomes maximised again.
![issue](https://user-images.githubusercontent.com/9505900/81497119-50778480-92b4-11ea-9c34-eec8590c6cc0.gif)

Repro steps:
- Ensure window is maximised
- Click and drag the title bar so that the window becomes smaller
- Drag the window around a bit (**Ensure left mouse button is held down**)
- Drag the title bar back to the top of the screen and release the mouse button.
- The window should auto-snap back to maximised size and the screen will not redraw properly.

This only works if the mouse button is held down throughout. If you release it when the window is smaller, everything works just fine. Let me know if you need any more info :) I'm loving the editor so far btw!

**Comment by doczi-dominik** [comment]
To me, this also happens when launching a fullscreen program using the `console` plugin.

I am using Arch Linux (kernel 5.4.41 LTS) with bspwm. The program in question is the DOME game engine, which also uses SDL2 (if that matters). This makes it extra pain to toggle treeview and toggle the console for the window to refresh completely.

**Comment by rxi** [comment]
@yyamdev Thanks for providing a gif and steps explaining how to reproduce this, it makes things a lot easier!

@doczi-dominik If this change doesn't fix your problem feel free to open a new issue for your case
