### ISSUE TITLE
Paste duplication

### ISSUE THREAD

**Issue by ajstarks** [rxi/lite#69]
Steps to reproduce:

1. Cut text via Ctrl-X
2. Paste via Ctrl-V
3. The text is pasted twice

**Comment by Gavin-Holt** [comment]
I have tried to reproduce this, and cannot. 
My system is Windows 10 and Lite version 1.03 (‎09 ‎May ‎2020).
It may be helpful to know which OS and version you are using.

Kind Regards Gavin Holt

**Comment by ajstarks** [comment]
Linux Fedora 32, ThinkPad X1 Carbon 5th Generation, 8GB RAM

**Comment by rxi** [comment]
lite uses SDL to manage it's clipboard, it does this through simple `set` and `get` functions provided by SDL -- as this seems to only be an issue for you specifically the bug is more likely to be in SDL or some other layer and thus is something that won't be fixed in lite directly. This may be something that you instead need to bring up with the SDL team.
