### ISSUE TITLE
Capslock mapped to Control doesn't map to Control inside lite (Manjrao/KDE Plasma)

### ISSUE THREAD

**Issue by hugows** [rxi/lite#8]
Hello,
I found this quite curious - no shortcuts (eg C-f) were working until I tried the real Control key and suddenly the editor made sense ;)

There are no other GUI applications where this happens. Any tips on how to fix it?
After 20 years its really hard to not use Caps-As-Control...

**Comment by rxi** [comment]
Interesting! Would you be able to print the value of `k` (`print(k)`) at the top of [this function](https://github.com/rxi/lite/blob/master/data/core/keymap.lua#L55) and let me know what key it's seeing it as?

If it's being reported as `capslock` instead of some variant of `control` I don't feel there's much I can do about it, but you can modify [this plugin](https://raw.githubusercontent.com/rxi/lite-plugins/master/macmodkeys.lua) to remap it in-program to ctrl. If it *is* being reported as some variant of `control` then we can add it to the table at the top of the `keymap.lua` file, in which case feel free to make a pull request.

**Comment by hugows** [comment]
It prints `capslock` indeed. Thanks for the tips!

**Comment by hugows** [comment]
For some reason the plugin string replacements weren't working for me - I had to rewrite `macmodkeys.lua `like this instead:


```
local function remap_key(k)
  local map = {
    command = "ctrl",
    option = "alt",
    capslock = "left ctrl"
  }
  if map[k] then
    return map[k]
  end
  return k
end
```
